# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ellucas <ellucas@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/03 14:28:12 by ellucas           #+#    #+#              #
#    Updated: 2025/04/03 17:29:47 by ellucas          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = pipex

INC_DIR = includes/
LIBFT_DIR = $(INC_DIR)libft/
LIBFT = $(LIBFT_DIR)libft.a
SRCS_DIR = srcs/
OBJ_DIR = obj/

CFLAGS = -Wall -Wextra -Werror -g

CC = gcc

SRCS = $(wildcard $(SRCS_DIR))